### ISSUE TITLE
Precido de Ajuda para pegar um campo.

### ISSUE THREAD

**Issue by sclFabio** [akretion/nfelib#112]
Olá, estou aprendendo a utilizar a biblioteca e dando meus primeiros passos com NF-e.  Eu preciso pegar o campo:

 produto = nfe.NFe.infNFe.det.prod.xProd
 
 estou obtendo como retorno o seguinte erro:
 
 AttributeError: 'list' object has no attribute 'prod'.

Consigo acessar os outros campos do xml menos esse, existe alguma coisa de diferente nele?. Estou seguindo normalmente o método de seleção apresentado na página inicial, se eu selecionar somente nfe.NFe.infNFe.det obtenho todo o campo "det".

Agradeço desde já.

**Comment by rvalyi** [comment]
Ola é porque o attributo det é uma lista mesmo. A lista das linhas da NFe no caso.
ai depois precisa de uma base com Python. vc pode mostrar o primeiro elemento da lista com ...infNFe.det[0].xProd

ou vc pode fazer um loop, por exemplo:
for item in ...infNFe.det:
    print(item.xProd)

...

**Comment by sclFabio** [comment]
Boa tarde, entendi. Vou testar aqui, qualquer coisa volto a perguntar.

Muito obrigado.
