### ISSUE TITLE
Não traz o nó 'protNFe'

### ISSUE THREAD

**Issue by souluanf** [akretion/nfelib#19]
Não consigo pegar os atributos de protNFe. Quando é feito o parse do arquivo, não é carregado este nós junto. Por favor, me ajudem com isso. Desde já, grato.

**Comment by picinatto** [comment]
@souluanf você conseguiu resolver isso? Estou com o mesmo problema.

**Comment by rvalyi** [comment]
@picinatto segura ai que em breve vem noticias boas sobre essa lib (nova branch ABSURDAMENTE melhor e mais fácil de usar).

**Comment by picinatto** [comment]
> @picinatto segura ai que em breve vem noticias boas sobre essa lib (nova branch ABSURDAMENTE melhor e mais fácil de usar).

Show! Obrigado! Parabéns pelo trabalho

**Comment by picinatto** [comment]
> @picinatto segura ai que em breve vem noticias boas sobre essa lib (nova branch ABSURDAMENTE melhor e mais fácil de usar).

Show! Obrigado! Parabéns pelo trabalho
