### ISSUE TITLE
Sequencia da tag do imposto de importação

### ISSUE THREAD

**Issue by renatonlima** [akretion/nfelib#31]
Importando uma NF-e de importação direta (NF-e de entrada de mercadoria através de importação) A tag II está na posição errada, em um na NF-e válida:

<img width="470" alt="Captura de Tela 2021-07-19 às 19 55 42" src="https://user-images.githubusercontent.com/211005/126237863-a25751f9-068e-4f33-b6c5-f4b70079d99e.png">

Importando essa NF-e e exportando através do nfelib:

<img width="376" alt="Captura de Tela 2021-07-19 às 19 57 56" src="https://user-images.githubusercontent.com/211005/126237993-a91c8752-9dc6-42e6-8f30-d006ffc3697d.png">

**Comment by rvalyi** [comment]
seria bom vc subir uma branch com seu patch para ver a melhor forma de resolver. Pessoal esse bug é real com as notas de importações. E o primeiro bug real que pegamos com o nfelib depois de emitir milhares de notas de diversas situaçoes em prod por mais de um ano.
