### ISSUE TITLE
Instalação quebrando

### ISSUE THREAD

**Issue by florencioq** [akretion/nfelib#34]
Prezados amigos, 

Os últimos Commits estão quebrando a instalação:
 
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-66ksj8xy/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-66ksj8xy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ref5mt4v
       cwd: /tmp/pip-req-build-66ksj8xy/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/nfelib
  copying nfelib/__init__.py -> build/lib/nfelib
  running egg_info
  creating nfelib.egg-info
  writing nfelib.egg-info/PKG-INFO
  writing dependency_links to nfelib.egg-info/dependency_links.txt
  writing requirements to nfelib.egg-info/requires.txt
  writing top-level names to nfelib.egg-info/top_level.txt
  writing manifest file 'nfelib.egg-info/SOURCES.txt'
  warning: Failed to find the configured license file 'LICENSE'
  reading manifest file 'nfelib.egg-info/SOURCES.txt'
  writing manifest file 'nfelib.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/nfelib
  copying build/lib/nfelib/__init__.py -> build/bdist.linux-x86_64/wheel/nfelib
  running install_egg_info
  Copying nfelib.egg-info to build/bdist.linux-x86_64/wheel/nfelib-1.0.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  ----------------------------------------
  ERROR: Failed building wheel for nfelib

Eu voltei os últimos 7 commits e ele volta a instalar.

Obrigado e abraços cordiais a todos.

Florêncio

**Comment by rvalyi** [comment]
Valeu pelo report @florencioq!
Eu acredito que eu acabei de resolver o problema com esse commit: https://github.com/akretion/nfelib/commit/e49b52e9186f6e143264074f81ce88a611a82c29

Testei com instalação local e não mostrava esse problema, foi mal.

Pode confirmar se resolveu para vc tb?

Caso isso não resolve, vc pode dar um pin no commit 86832c69ceed8809eecbd536cf55fdcd7aec044b que é a ultima versão de antes da atualização com o empacotamento.

**Comment by florencioq** [comment]
Olá amigo. Voltou a instalar. Obrigado.
