### ISSUE TITLE
Complexity of generate code

### ISSUE THREAD

**Issue by cclauss** [akretion/nfelib#35]
Your call...  This might not be important...

[McCabe](https://pypi.org/project/mccabe/) measure of [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) is built into flake8 with a recommended default value of 10.

Perhaps this [block of generated code](https://github.com/akretion/nfelib/blob/master_gen_v4_00/nfelib/v4_00/distDFeInt.py#L177-L671) might be a bit too complex.

$ `flake8 . --select=C --max-complexity=37`
```
./nfelib/v4_00/retDistDFeInt.py:177:1:      C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retConsStatServ.py:177:1:      C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retEnvEvento.py:177:1:    C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retInutNFe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/distDFeInt.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retEnvCCe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retEnvEventoCancNFe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retConsReciNFe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retEnviNFe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retConsCad.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retConsSitNFe.py:177:1: C901 'TryExcept 177' is too complex (164)
./nfelib/v4_00/retEnvConfRecebto.py:177:1: C901 'TryExcept 177' is too complex (164)
```

**Comment by rvalyi** [comment]
@cclauss please be patient, I'm extremely busy these days but I promise I have a good definitive fix for all of these code smells from generateDS. Stay tuned, big news coming...

**Comment by rvalyi** [comment]
Hello @cclauss so finally after quite some work I published a brand new version of nfelib. It's now generated using xsdata and it's much cleaner. You can find information in the README https://github.com/akretion/nfelib
