### ISSUE TITLE
Erro de módulo não encontrado

### ISSUE THREAD

**Issue by florencioq** [akretion/nfelib#36]
Bom dia a todos!

A versão atual, quando vamos utilizar, dá o seguinte erro:

>>> from nfelib.v4_00 import leiauteNFe_sub as parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nfelib.v4_00'

Um fork que tenho de 13 commits atrás funciona normalmente.

Cordiais saudações a todos.
Florêncio

**Comment by rvalyi** [comment]
Ola Florêncio, vc poderia tentar novamente com `pip install nfelib==1.1` e confirmar se ta tudo OK agora?

**Comment by dsicari** [comment]
Mesmo erro por aqui, quando tento o comando do @rvalyi  tenho o seguinte retorno: 

`ERROR: Could not find a version that satisfies the requirement nfelib==1.1 (from versions: 0.1)
ERROR: No matching distribution found for nfelib==1.1`

**Comment by rvalyi** [comment]
@florencioq , @dsicari vcs poderiam tentar de novo? Sera se vcs nao estao fazendo algo errado, para mim funciona perfeitamente, fiz agora:
![2021-08-23_10-44](https://user-images.githubusercontent.com/16926/130458032-d7f52a09-b78d-4e30-9de2-91bb58c02d73.png)


Mas não é so para mim que funciona, vcs podem ver aqui os testes da nossa localização do ERP Odoo 12.0 que usa a nfelib 1.1 passando certinho:
https://github.com/OCA/l10n-brazil/pull/1575

Isso exactamente com essa mudança no requirements.txt para pegar a versão publicada:
https://github.com/OCA/l10n-brazil/pull/1575/commits/c924636f1ab3c3a9b3fdf2042191c4958321213e

**Comment by rvalyi** [comment]
@florencioq , @dsicari podem confirmar se funciona para vcs? Sera se vcs não precisavam desinstalar a antiga versão antes?

**Comment by florencioq** [comment]
Desculpa o atraso pessoal. Vou olhar agora.

**Comment by florencioq** [comment]
Funcionando normal aqui com "pip install nfelib==1.1"
Obrigado @rvalyi !

**Comment by rvalyi** [comment]
show!
