### ISSUE TITLE
Não tem o metodo get_emit()

### ISSUE THREAD

**Issue by chapzin** [akretion/nfelib#5]
AttributeError: 'NoneType' object has no attribute 'get_emit'
Fiz de acordo com o exemplo mostrado e estou recebendo esse erro

**Comment by rvalyi** [comment]
Ola @chapzin, eh provavel que o parsing nao deu certo no seu caso, talvez porque tentou fazer o parsing the uma nota processada ou algo assim. Tem que ser o pedaço de XML na tag <NFe> apenas. Se o XML começa pela tag <nfeProc> por examplo, tem que passar apenas a parte da tag <NFe> dentro (usando lxml por examplo).

Pelo jeito a lib consegue gerir todos XML do XSD. Mas na questao do parsing foco apenas nos layouts de Nfe, inutilizaçao e consulta para limitar o tamanho da lib, ja que os outros XML derivam desses 3 XML de forma muito trivial.

Nessa semana vou subir uma versao atualizada, que traz uns fixes pro Python 2 e tb traz varias melhorias qdo usado no ERP livre Odoo...

**Comment by rvalyi** [comment]
entao fechando porque nao eh um bug mas apenas um mal uso devido a falta de documentaçao. Vou atualizar a doc em breve.
