### ISSUE TITLE
Esse pacote foi depreciado

### ISSUE THREAD

**Issue by craines** [akretion/nfelib#51]
Vi que a ultima atualização foi em 2021 e que tem muitas issues aberta.
Gostaria de saber esse pacote existe ainda ou se ele foi movido para outro lugar

**Comment by rvalyi** [comment]
Ola @craines na verdade a gente ta querendo substituir a geraçao do generateDS pela geração do xsdata que ta com codigo bem melhor e gera codigo melhor. A manutençao com generateDS eh bem tranquila comparando com as outras libs com codigo manual.
Ja tem uma branch com essa nova geração: https://github.com/akretion/nfelib/tree/master-xsdata
E logo ira receber atualizaçoes de schema.

A questão eh que usamos no ERP Odoo, fiz uns 3 PRs de refator la para fazer essa migração e eu começei a fazer uns PRs para trocar, mas ainda nao terminamos 100%:
https://github.com/OCA/l10n-brazil/pulls?q=is%3Apr+is%3Aopen+xsdata

Em questões de algumas semanas teremos isso 100% e ai eu irei trocar branch padrão do nfelib pela branch xsdata e atualizar os schemas (eh melhor atualizar o Odoo sem mudar de versão de schema primeiro). Então pode seguir o projeto que tera atualizaçôes logo.

**Comment by craines** [comment]
Perfeito!
Então eu posso usar a branch [master-xsdata](https://github.com/akretion/nfelib/tree/master-xsdata) ?
Vocês tem Discord ou algo do tipo, onde a comunidade consiga ajuda a evoluir o projeto.

**Comment by rvalyi** [comment]
o melhor é vc usar os issues e pull requests mesmo eu acho. Vai te faltar um pouco de documentação para usar a branch xsdata, mas olha nos testes que eu já adaptei e olha os commits nos 3 PRs do Odoo eventualmente.

Para a gente minimizar o diff na migração do Odoo é possivel que nao vamos atualizar os schemas agora na branch principal, mas vc pode faze-lo num fork ate a gente fazer essa migração.

Eu accredito que mudar pro xsdata vai ajudar bastante o projeto a mudar de patamar e que as coisas vão accelerar porque realmente ta muito mais tranquilo manter do que as libs escritas manualmente. Eu espero que em um mes a gente faz essa migração... cc @renatonlima 

Se vc for gerir a lib de novo com xsdata se liga so nessa pegadinha https://github.com/akretion/nfelib/issues/40
basicamente eu usei um patch de uma linha no xsdata (eu acho que o nome do arquivo mudou mas é facil ver qual é), isso para nao ter que alterar muito a logica do marshalling/unmarshalling assim como expliquei no issue.

Atts.

**Comment by craines** [comment]
Blz, muito obrigado!

**Comment by rvalyi** [comment]
@craines eu acabei dando uma atualizada nos esquemas ainda com a tecnologia generateDS. Acabei de publicar a versão 1.3.0 que conta com os esquemas:
Pacote de Liberação nº 9i (Novo leiaute da NF-e, NT 2021.004 v.1.00d). Publicado em 17/05/22

Mas essa sera a ultima versão legacy, agora é rumo xsdata!

**Comment by rvalyi** [comment]
Ola @craines foi publicada a nova versão com xsdata, eu aconselho olhar o README e o codigo aqui https://github.com/akretion/nfelib
