### ISSUE TITLE
Gerar danfe

### ISSUE THREAD

**Issue by luanpontes100** [akretion/nfelib#83]
Com essa biblioteca, é possível montar o PDF de um DANFE com os dados de um DANFE já gerado e validado?

**Comment by antoniospneto** [comment]
@luanpontes100 Não, esse não é o objetivo desta biblioteca.

**Comment by thomcode** [comment]
que triste

**Comment by rvalyi** [comment]
> que triste

existem vários projetos que aceitam como entrada um XML de uma nota assinada e te devopvem o pdf do DANFE. Um deles que  gente usa em conjunto com a nfelib é esse 
https://github.com/erpbrasil/erpbrasil.edoc.pdf
Mas é provável que tenha alternativas mais limpas e mais leves pro PDF do DANFE.

**Comment by rvalyi** [comment]
esta até documentado no README agora https://github.com/akretion/nfelib?tab=readme-ov-file#como-usar
