### ISSUE TITLE
Inconpatibilidade com AWS Lambda 

### ISSUE THREAD

**Issue by c-reschke** [akretion/nfelib#90]
Olá. 

Estou tentando utilizar a lib com AWS Lambda mas não estou conseguindo.
Mesmo criando uma layer na hora de importar da erro de timeout.

```
import json
from nfelib.v4_00 import leiauteNFe_sub as parser



def lambda_handler(event, context):
    # TODO implement
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }

```

![image](https://github.com/akretion/nfelib/assets/6054359/8aa11a03-359e-4cb1-8fef-bd75e8095ecd)

Alguém já teve esse problema, conseguem me ajudar?

**Comment by rvalyi** [comment]
uma coisa que eu vejo é que vc esta usando os antigos "bindings" legacy da nfelib 1.x que era gerida pelo GenerateDS. Uma das primeiras coisas que vc poderia fazer é testar com os bindings geridos pelo xsdata assim como documentado no README.

**Comment by antoniospneto** [comment]
@c-reschke 

No erro que você reportou não há nenhum inidicio foi gerado por causa da lib, então penso a issue está relacionada ao uso do AWS Lambda não do nfelib..

**Comment by rvalyi** [comment]
Fechando porque me parece que o problema não vem do nfelib mesmo. Re-abrir caso for o caso e com mais detalhes por favor.
